config:
    # IDs & paths
    data_id: "datasets/detector"
    model_id: "classifier_nummut_sigmoid"
    models_dir: "vae_classifier/"

    # Training params
    iterations: 100
    num_classes: 96
    lagrange_param: 0.01
    batch_size: 500
    lr_encoder: 0.0005
    lr_decoder: 0.00005
    sigmoid_params: [5000,1000]

    # WANDB params
    enable_logging: True
    wandb_project_id: "vae_generator"

    # Network params
    num_hidden_layers: 5
    latent_dim: 10

    # Misc
    device: "cuda"