config:
    # IDs & paths
    data_id: "datasets/detector"
    model_id: "classifier_2"
    models_dir: "vae_classifier/"

    # Training params
    iterations: 100
    num_classes: 96
    lagrange_param: 0.001
    batch_size: 100
    lr_encoder: 0.005
    lr_decoder: 0.0005

    # WANDB params
    enable_logging: True
    wandb_project_id: "vae_generator"

    # Network params
    num_hidden_layers: 5
    latent_dim: 20

    # Misc
    device: "cuda"