config:
    # IDs & paths
    data_id: "datasets/detector"
    model_id: "ae_best_2_3"
    models_dir: "vae_classifier/"

    # Training params
    iterations: 10000
    num_classes: 96
    lagrange_param: 0.01
    batch_size: 115
    lr_encoder: 0.0000353
    lr_decoder: 0.000991595
    sigmoid_params: [5000,1000]

    # WANDB params
    enable_logging: True
    wandb_project_id: "vae_classification"

    # Network params
    num_hidden_layers: 1
    latent_dim: 14
    num_units: 271
    num_units_branch_mut: 1

    # Misc
    device: "cuda"